### ISSUE TITLE
Android Terminal APK Crashes

### ISSUE THREAD

**Issue by iSDP** [felis/USB_Host_Shield_2.0#74]
Here's the stacktrace: 
01-24 12:19:22.771  26986-26986/com.victorint.android.usb D/dalvikvm﹕ DexOpt: couldn't find field Landroid/app/ActivityThread;.mActiveResources
01-24 12:19:22.771  26986-26986/com.victorint.android.usb W/dalvikvm﹕ VFY: unable to resolve instance field 1
01-24 12:19:22.771  26986-26986/com.victorint.android.usb D/dalvikvm﹕ VFY: replacing opcode 0x54 at 0x0006
01-24 12:19:22.771  26986-26986/com.victorint.android.usb D/dalvikvm﹕ DexOpt: couldn't find field Landroid/app/ActivityThread;.mPackages
01-24 12:19:22.771  26986-26986/com.victorint.android.usb W/dalvikvm﹕ VFY: unable to resolve instance field 4
01-24 12:19:22.771  26986-26986/com.victorint.android.usb D/dalvikvm﹕ VFY: replacing opcode 0x54 at 0x0000
01-24 12:19:22.801  26986-26986/com.victorint.android.usb D/AndroidRuntime﹕ Shutting down VM
01-24 12:19:22.801  26986-26986/com.victorint.android.usb W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41529d40)
01-24 12:19:22.811  26986-26986/com.victorint.android.usb E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.victorint.android.usb, PID: 26986
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.victorint.android.usb/com.victorint.android.usb.ArduinoTerminalActivity}: android.util.AndroidRuntimeException: You cannot combine custom titles with other title features
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:126)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.util.AndroidRuntimeException: You cannot combine custom titles with other title features
            at com.android.internal.policy.impl.PhoneWindow.requestFeature(PhoneWindow.java:261)
            at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2830)
            at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3085)
            at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:286)
            at android.app.Activity.setContentView(Activity.java:1929)
            at com.victorint.android.usb.TerminalViewable.setActivity(TerminalViewable.java:92)
            at com.victorint.android.usb.ArduinoTerminalActivity.createAndSetViews(ArduinoTerminalActivity.java:23)
            at com.victorint.android.usb.UsbActivity.onCreate(UsbActivity.java:223)
            at com.victorint.android.usb.ArduinoTerminalActivity.onCreate(ArduinoTerminalActivity.java:17)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:126)
            at dalvik.system.NativeStart.main(Native Method)

I'm running android 4.2.2  on a nexus 5, probably the reason why BT won't work either.

**Comment by Lauszus** [comment]
Closing due to lack of feedback. Reopen if necessary.
